name: Searcade Auto Login

on:
  workflow_dispatch: # 支持手动触发
  schedule:
    - cron: '30 23 * * *' # 示例：每天北京时间早上 7:30 运行

jobs:
  run-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install playwright requests
          playwright install chromium

      - name: Execute Login Script
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python main.py

      - name: Upload Artifacts (Screenshots)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots
          path: "*.png"
